//go:build gcp_conformance

package main

import (
	"encoding/csv"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// matrixVersion is the schema version of the generated artifacts.
const matrixVersion = 1

// MatrixDoc is the canonical machine-readable matrix. It contains NO volatile
// fields (no timestamp, no commit sha) so a regenerate-and-diff drift check is
// exact.
type MatrixDoc struct {
	Version int           `json:"version"`
	Summary MatrixSummary `json:"summary"`
	Cells   []Cell        `json:"cells"`
}

// MatrixSummary is the rollup over all cells.
type MatrixSummary struct {
	Total            int                       `json:"total"`
	ByState          map[string]int            `json:"by_state"`
	ByTransport      map[string]map[string]int `json:"by_transport"`
	ByService        map[string]map[string]int `json:"by_service"`
	GRPCOnlyServices []string                  `json:"grpc_only_services,omitempty"`
}

// stateOrder fixes the reporting order of states (best to worst).
var stateOrder = []string{StateGA, StateLimited, StatePreview, StateUnsupported}

// Render sorts cells deterministically and builds the matrix document.
func Render(cells []Cell, grpcOnly []string) MatrixDoc {
	sorted := append([]Cell(nil), cells...)
	sort.Slice(sorted, func(i, j int) bool {
		a, b := sorted[i], sorted[j]
		if a.Service != b.Service {
			return a.Service < b.Service
		}
		if a.Operation != b.Operation {
			return a.Operation < b.Operation
		}
		return a.Transport < b.Transport
	})

	sum := MatrixSummary{
		Total:       len(sorted),
		ByState:     map[string]int{},
		ByTransport: map[string]map[string]int{},
		ByService:   map[string]map[string]int{},
	}
	for _, c := range sorted {
		sum.ByState[c.State]++
		bump(sum.ByTransport, c.Transport, c.State)
		bump(sum.ByService, c.Service, c.State)
	}
	sum.GRPCOnlyServices = grpcOnly

	return MatrixDoc{Version: matrixVersion, Summary: sum, Cells: sorted}
}

func bump(m map[string]map[string]int, key, state string) {
	if m[key] == nil {
		m[key] = map[string]int{}
	}
	m[key][state]++
}

// WriteMatrix writes fidelity-matrix.{json,md,csv} into dir.
func WriteMatrix(dir string, doc MatrixDoc) error {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	if err := writeJSON(filepath.Join(dir, "fidelity-matrix.json"), doc); err != nil {
		return err
	}
	if err := writeMarkdown(filepath.Join(dir, "fidelity-matrix.md"), doc); err != nil {
		return err
	}
	return writeCSV(filepath.Join(dir, "fidelity-matrix.csv"), doc)
}

func writeJSON(path string, doc MatrixDoc) error {
	b, err := json.MarshalIndent(doc, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, append(b, '\n'), 0o644)
}

func writeCSV(path string, doc MatrixDoc) error {
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()
	w := csv.NewWriter(f)
	defer w.Flush()
	if err := w.Write([]string{"service", "operation", "transport", "state", "reason"}); err != nil {
		return err
	}
	for _, c := range doc.Cells {
		if err := w.Write([]string{c.Service, c.Operation, c.Transport, c.State, c.Reason}); err != nil {
			return err
		}
	}
	return w.Error()
}

func writeMarkdown(path string, doc MatrixDoc) error {
	var b strings.Builder
	b.WriteString("# GCP emulator fidelity matrix\n\n")
	b.WriteString("Generated by `tools/fidelitygen` (`make gen-gcp-fidelity-matrix`) from the emulator's\n")
	b.WriteString("operation registry, the vendored Discovery schemas, the conformance report, and\n")
	b.WriteString("`docs/fidelity-overrides.yaml`. Do not edit by hand.\n\n")
	b.WriteString("States: **ga** = supported and wire-conformant · **limited** = implemented with a " +
		"declared caveat · **preview** = not covered by the stability promise · " +
		"**unsupported** = not implemented.\n\n")

	fmt.Fprintf(&b, "Cells: **%d**\n\n", doc.Summary.Total)

	b.WriteString("## Rollup\n\n| state | count |\n| --- | --- |\n")
	for _, s := range stateOrder {
		fmt.Fprintf(&b, "| %s | %d |\n", s, doc.Summary.ByState[s])
	}

	b.WriteString("\n### By transport\n\n| transport | ga | limited | preview | unsupported |\n| --- | --- | --- | --- | --- |\n")
	for _, tr := range []string{"rest", "grpc"} {
		m := doc.Summary.ByTransport[tr]
		fmt.Fprintf(&b, "| %s | %d | %d | %d | %d |\n",
			tr, m[StateGA], m[StateLimited], m[StatePreview], m[StateUnsupported])
	}
	if len(doc.Summary.GRPCOnlyServices) > 0 {
		fmt.Fprintf(&b, "\ngRPC-only services (no REST transport): %s.\n",
			strings.Join(doc.Summary.GRPCOnlyServices, ", "))
	}

	services := make([]string, 0, len(doc.Summary.ByService))
	for svc := range doc.Summary.ByService {
		services = append(services, svc)
	}
	sort.Strings(services)

	for _, svc := range services {
		m := doc.Summary.ByService[svc]
		fmt.Fprintf(&b, "\n## %s\n\n", svc)
		fmt.Fprintf(&b, "_%d cell(s): ga=%d limited=%d preview=%d unsupported=%d_\n\n",
			totalStates(m), m[StateGA], m[StateLimited], m[StatePreview], m[StateUnsupported])
		b.WriteString("| operation | transport | state | reason |\n| --- | --- | --- | --- |\n")
		for _, c := range doc.Cells {
			if c.Service != svc {
				continue
			}
			fmt.Fprintf(&b, "| %s | %s | %s | %s |\n",
				c.Operation, c.Transport, c.State, mdCell(c.Reason))
		}
	}
	return os.WriteFile(path, []byte(b.String()), 0o644)
}

func totalStates(m map[string]int) int {
	n := 0
	for _, v := range m {
		n += v
	}
	return n
}

// mdCell escapes a value for a markdown table cell.
func mdCell(s string) string {
	s = strings.ReplaceAll(s, "|", "\\|")
	s = strings.ReplaceAll(s, "\n", " ")
	if s == "" {
		return "—"
	}
	return s
}
