ALTER TABLE jc_gcs_objects ADD COLUMN IF NOT EXISTS kms_key_name TEXT NOT NULL DEFAULT '';
ALTER TABLE jc_gcs_objects ADD COLUMN IF NOT EXISTS wrapped_dek BYTEA;
ALTER TABLE jc_gcs_objects ADD COLUMN IF NOT EXISTS cse_key_sha256 TEXT NOT NULL DEFAULT '';
